### ISSUE TITLE
BCMDL Crash

### ISSUE THREAD

**Issue by NickGurMatic69** [gdkchan/SPICA#25]
File https://mega.nz/#!BthkzKga!82JKeXp2o8H1AKB7epE4hQELNYjb8pYbFub4uBA2cE8

and error
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.BinaryReader.ReadChar()
   at SPICA.Serialization.BinaryDeserializer.ReadString()
   at SPICA.Serialization.BinaryDeserializer.ReadValue(Type Type, Boolean IsRef)
   at SPICA.Serialization.BinaryDeserializer.ReadReference(Type Type, FieldInfo Info)
   at SPICA.Serialization.BinaryDeserializer.ReadObject(Type ObjectType, Boolean IsRef)
   at SPICA.Serialization.BinaryDeserializer.ReadValue(Type Type, Boolean IsRef)
   at SPICA.Serialization.BinaryDeserializer.ReadReference(Type Type, FieldInfo Info)
   at SPICA.Serialization.BinaryDeserializer.ReadList(Type Type, Boolean Range, Int32 Length)
   at SPICA.Serialization.BinaryDeserializer.ReadReference(Type Type, FieldInfo Info)
   at SPICA.Serialization.BinaryDeserializer.ReadObject(Type ObjectType, Boolean IsRef)
   at SPICA.Serialization.BinaryDeserializer.ReadValue(Type Type, Boolean IsRef)
   at SPICA.Serialization.BinaryDeserializer.ReadReference(Type Type, FieldInfo Info)
   at SPICA.Serialization.BinaryDeserializer.ReadObject(Type ObjectType, Boolean IsRef)
   at SPICA.Serialization.BinaryDeserializer.ReadValue(Type Type, Boolean IsRef)
   at SPICA.Serialization.BinaryDeserializer.Deserialize[T]()
   at SPICA.Formats.CtrGfx.GfxDictionary`1.SPICA.Serialization.ICustomSerialization.Deserialize(BinaryDeserializer Deserializer)
   at SPICA.Serialization.BinaryDeserializer.ReadObject(Type ObjectType, Boolean IsRef)
   at SPICA.Serialization.BinaryDeserializer.ReadValue(Type Type, Boolean IsRef)
   at SPICA.Serialization.BinaryDeserializer.ReadReference(Type Type, FieldInfo Info)
   at SPICA.Serialization.BinaryDeserializer.ReadObject(Type ObjectType, Boolean IsRef)
   at SPICA.Serialization.BinaryDeserializer.ReadValue(Type Type, Boolean IsRef)
   at SPICA.Serialization.BinaryDeserializer.ReadObject(Type ObjectType, Boolean IsRef)
   at SPICA.Serialization.BinaryDeserializer.ReadValue(Type Type, Boolean IsRef)
   at SPICA.Serialization.BinaryDeserializer.Deserialize[T]()
   at SPICA.Formats.CtrGfx.Gfx.Open(Stream Input)
   at SPICA.WinForms.Formats.FormatIdentifier.IdentifyAndOpen(String FileName, H3DDict`1 Skeleton)
   at SPICA.WinForms.Formats.FileIO.Merge(String[] FileNames, Renderer Renderer, H3D Scene)
   at SPICA.WinForms.FrmMain.Open(Boolean MergeMode)
   at SPICA.WinForms.FrmMain.TBtnOpen_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1099.0 built by: NETFXREL4STAGE
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
SPICA.WinForms
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Kek/Downloads/spica_lastest/SPICA.WinForms.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1099.0 built by: NETFXREL4STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1099.0 built by: NETFXREL4STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1099.0 built by: NETFXREL4STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
OpenTK
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0
    CodeBase: file:///C:/Users/Kek/Downloads/spica_lastest/OpenTK.DLL
----------------------------------------
OpenTK.GLControl
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0
    CodeBase: file:///C:/Users/Kek/Downloads/spica_lastest/OpenTK.GLControl.DLL
----------------------------------------
SPICA
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Kek/Downloads/spica_lastest/SPICA.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1099.0 built by: NETFXREL4STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1099.0 built by: NETFXREL4STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1099.0 built by: NETFXREL4STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
SPICA.Rendering
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Kek/Downloads/spica_lastest/SPICA.Rendering.DLL
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1099.0 built by: NETFXREL4STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by gdkchan** [comment]
This seems to be a very old version of the cgfx format (probably one of the first versions), and the format does have bigger differences from other, newer cgfx files. For example, instead of a <pointer><length> structure for the lists if seems to have a pointer that points to the length followed by data, the DATA section doesn't even exist, and the number of sub-sections pointer is way smaller too. I think that supporting that will be quite a bit of work so I will put that at hold for now.

**Comment by KekMcGee** [comment]
I found some more incompatible files from Mii Plaza's Spotpass puzzles. Files: https://mega.nz/#!VhpBzbST!BEmlNKglNag2OCNR-0_E5zVceNLiKJ6ydP8SxM-p-fE

**Comment by sachaw** [comment]
Just ran into this issue with some new files from pokemon Ultra Sun:
https://drive.google.com/file/d/1NJ9HOxH0lZb2abIObC8nAIl9qXbTrMt3/view?usp=sharing
@gdkchan I believe this should't be an old version of the format, so maybe a separate issue?

**Comment by RhythmThief2012** [comment]
A lot of this type of file was left over in Rhythm Thief. It has earlier(?) versions of a majority of the BC formats. (Specifically: BCMDL, BCSKLA, BCCAM, BCENV, BCMATA, BCLGT, CRES) 
https://drive.google.com/file/d/1OOc51kGKuXCZb_oJnkU_0990ZtN34ha1/view?usp=sharing 
@gdkchan Hope this helps!
